# note: these values are automatically replaced when initialized with roverctl
name: analyser
author: ambra
source: github.com/ambra19/analyser.git
version: 0.0.1
description: Subscriber service that receives input from the energy service

# The alias "as: controller" allows this service to be recognized as "controller"
# by other components (like the actuator), even if its actual name is different.
# This allows us to change the name of the service without breaking the system.
as: controller

commands:
  build: echo "no build command needed"
  run: ./src/main.py
  
inputs:
  - service: energy
    streams:
      - energy
outputs:
  - decision

configuration:
  - name: speed
    type: number
    value: 0.2
    tunable: true
